core/trueseeing/patch.py, core/trueseeing/shell.py
=> Patching APK

trueseeing/signature/manifest.py
a.k.a. InsecureBank v2 sniffable intent usage
=> Flagging inadvent-specific intent data pattern as such

trueseeing/context.py
=> Updated apktool to 2.2.4

trueseeing/store.py
=> Mapping to class before query

trueseeing/signature/security.py
Fixes insecure webview detector; broken patterns in invocation queries.  Meh.
=> Fixing insecure webview detector

trueseeing/shell.py
=> Adding help and fixing broken grab lists

trueseeing/grab.py
=> Resolving package path from package manager information dump

trueseeing/flow/data.py
Enabling backtracking of p* registers.  That. is. the. fix. for. R.8.
This PR fixes #88 .
=> Experimentally enabling backtracking of p* registers

trueseeing/exploit.py, trueseeing/shell.py
Disables some form of the declarative TLS certificate pinning (API>=24).
This PR partially solves #59 .
=> Enable to disable declarative TLS pinning

trueseeing/shell.py
=> Fixing help message

setup.py, trueseeing/_dummy.py
=> Dropping python2

trueseeing/signature/security.py
=> patch: prevent KeyError

pyproject.toml
=> Bumping Python version

trueseeing/app/grab.py, trueseeing/app/shell.py
=> Grab mode fixups

trueseeing/core/context.py
=> Placing workdirs next to targets

trueseeing/core/code/model.py, trueseeing/core/code/parse.py, trueseeing/core/flow/code.py, trueseeing/core/flow/data.py, trueseeing/core/literalquery.py, trueseeing/core/store.py, trueseeing/libs/store.s.sql
=> Performance fixes

trueseeing/core/code/parse.py, trueseeing/core/store.py
Fixes #150, completely nailing #143 down.
Example case run: 66.96s -> 59.92s (M1)
=> Batching ops/class-marks, calculating method-marks at DB

trueseeing/core/store.py, trueseeing/libs/store.0.sql, trueseeing/libs/store.1.sql
=> Using normal tables and calculating ops_p later

trueseeing/core/code/parse.py, trueseeing/libs/store.1.sql
Fixes #134, and should fix #127, #128 as well.
=> Experimentally laxing reflike

mypy.ini, pyproject.toml, trueseeing/app/exploit.py, trueseeing/app/grab.py, trueseeing/app/patch.py, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/code/model.py, trueseeing/core/code/parse.py, trueseeing/core/context.py, trueseeing/core/flow/code.py, trueseeing/core/flow/data.py, trueseeing/core/issue.py, trueseeing/core/report.py, trueseeing/core/sign.py, trueseeing/core/store.py, trueseeing/core/ui.py, trueseeing/signature/base.py, trueseeing/signature/battery.py, trueseeing/signature/crypto.py, trueseeing/signature/denial.py, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py, trueseeing/signature/privacy.py, trueseeing/signature/security.py
=> Introducing pflake8

trueseeing/app/shell.py, trueseeing/core/api.py, trueseeing/core/context.py
=> Enabling extensions to patch DB and extend signatures

pyproject.toml, trueseeing/app/shell.py
=> Typing necessary pieces

trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/report.py
=> Always note and generate reports in specified file or stdout 

trueseeing/core/api.py
=> Fixed single-file extensions

pyproject.toml, trueseeing/core/patch.py
=> Whitespace police

trueseeing/core/patch.py, trueseeing/signature/security.py
=> Using aapt2

trueseeing/app/shell.py, trueseeing/core/code/model.py, trueseeing/core/flow/data.py, trueseeing/core/ui.py
=> Propagating partial graph

trueseeing/core/literalquery.py, trueseeing/signature/crypto.py
=> Reporting offending API calls too

trueseeing/app/shell.py, trueseeing/signature/security.py
=> Adding rudimentary adb probe detector

trueseeing/app/fingerprint.py, trueseeing/app/inspect.py, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/context.py, trueseeing/core/patch.py, trueseeing/core/store.py, trueseeing/signature/crypto.py, trueseeing/signature/fingerprint.py, trueseeing/signature/privacy.py, trueseeing/signature/security.py
=> Experimentally excluding packages

trueseeing/app/shell.py, trueseeing/signature/fingerprint.py
=> Detecting native methods

trueseeing/app/shell.py, trueseeing/signature/fingerprint.py
=> Enumerating native architectures

trueseeing/signature/security.py
=> Expeirmentally detecting JQuery-based client-side XSS vectors

trueseeing/app/shell.py, trueseeing/signature/security.py
=> Experimentally detecting potential logging into file

trueseeing/signature/security.py
=> Experimentally evaluating CSP and fixes

trueseeing/app/shell.py, trueseeing/core/context.py, trueseeing/core/literalquery.py, trueseeing/signature/security.py
=> Evaluating NSC

trueseeing/signature/security.py
=> Mapping the correct directory for the android_asset URL

trueseeing/libs/template/report.html
=> Fixing broken template

trueseeing/libs/template/report.html
=> Reporting issues with 1-based index

trueseeing/libs/template/report.html
=> Generating TOC

pyproject.toml, trueseeing/app/exploit.py, trueseeing/app/fingerprint.py, trueseeing/app/grab.py, trueseeing/app/inspect.py, trueseeing/app/patch.py, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/context.py, trueseeing/core/patch.py, trueseeing/core/sign.py, trueseeing/core/store.py, trueseeing/core/tools.py, trueseeing/signature/base.py, trueseeing/signature/crypto.py, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py, trueseeing/signature/privacy.py, trueseeing/signature/security.py
=> Desynchronizing sigs/subprocesses

README.md, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/report.py
=> Cleanly separating output/format options

trueseeing/app/patch.py, trueseeing/core/patch.py, trueseeing/core/sign.py, trueseeing/core/tools.py
=> Invoking zipalign and patch fixup

trueseeing/core/literalquery.py
=> Fixing table name

trueseeing/core/context.py, trueseeing/core/store.py
=> Stabilizing store lifetime

.gitattributes, README.md, pyproject.toml, trueseeing/app/boot.py, trueseeing/app/exploit.py, trueseeing/app/patch.py, trueseeing/app/shell.py, trueseeing/core/asm.py, trueseeing/core/code/parse.py, trueseeing/core/context.py, trueseeing/core/patch.py, trueseeing/core/report.py, trueseeing/core/sign.py, trueseeing/core/store.py, trueseeing/libs/container/Dockerfile, trueseeing/libs/container/Dockerfile-zipalign, trueseeing/libs/container/android-sdk-build-tools-33.0.0.tar.gz, trueseeing/libs/container/asm.py, trueseeing/libs/container/disasm.py, trueseeing/libs/container/genkey.py, trueseeing/libs/container/resign.py, trueseeing/libs/container/sign.py, trueseeing/libs/container/unsign.py, trueseeing/libs/store.0.sql, trueseeing/libs/store.s.sql, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py, trueseeing/signature/security.py
=> Lifting APK handling process

pyproject.toml, trueseeing/core/asm.py, trueseeing/core/patch.py, trueseeing/core/sign.py, trueseeing/libs/container/build.sh
=> Prevent containers from included in packages

trueseeing/app/shell.py, trueseeing/core/asm.py
=> Specifing precise version in running container and help msg fix

trueseeing/libs/public_suffix_list.dat
=> Update public suffix list

Dockerfile, trueseeing/core/store.py, trueseeing/signature/base.py, trueseeing/signature/crypto.py, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py, trueseeing/signature/privacy.py, trueseeing/signature/security.py
=> Basing on 3.11 and marking RE as deterministic

trueseeing/core/flow/data.py
=> Experimentally limiting graph size

trueseeing/app/inspect.py, trueseeing/app/scan.py
=> Suppressing done indicator from scan mode when it is invoked from the inspect mode

pyproject.toml, trueseeing/app/inspect.py, trueseeing/core/ui.py
=> Coloring outputs in interactive inspecting mode sessions

trueseeing/app/shell.py, trueseeing/signature/manifest.py
=> Flagging cleartext traffic permitted status

trueseeing/signature/manifest.py
=> Considering fullBackupContent

trueseeing/core/ui.py, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py
=> Slightly refined hostlike filter

pyproject.toml, trueseeing/__init__.py, trueseeing/app/inspect.py, trueseeing/core/store.py
- Dependency cleanup
- Make REGEXP available also for bytes
- Adding basic filename/string search
- Bumping version
=> Prepare 2.1.8

trueseeing/core/ui.py
=> Flushing stdout/err

.gitattributes, README.md, trueseeing/__init__.py
- Adding notice
- Dropping dead code
- Bumping version
=> Prepare 2.1.8.1

Dockerfile, trueseeing/app/inspect.py, trueseeing/core/device.py
=> Adding device related commands for inspect mode

trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/flow/data.py
=> Make graph size limit tunable

trueseeing/signature/fingerprint.py
=> Picking up architectures

trueseeing/app/exploit.py, trueseeing/app/inspect.py, trueseeing/core/patch.py
=> Adapting the new way

trueseeing/app/inspect.py
=> Retargetting fix for normal case

trueseeing/core/report.py
=> Re-creating logs as CI report

trueseeing/app/inspect.py
=> Experimentally counting fragment-like

trueseeing/app/shell.py, trueseeing/core/ui.py
=> Deprecating old way

trueseeing/signature/manifest.py
=> Correctly score cleartext traffic eligibility

trueseeing/app/shell.py
=> Dropping into inspect mode if neither mode nor files given

trueseeing/app/shell.py, trueseeing/signature/security.py
=> Adding SP detector

trueseeing/core/code/parse.py, trueseeing/core/store.py
=> Method mapping choke fixup

trueseeing/app/inspect.py
=> Showing package in info command

trueseeing/core/context.py, trueseeing/signature/manifest.py
=> Marking tentative scenarios of backup attacks

.github/workflows/build.yaml
=> Adding CI actions

trueseeing/core/flow/data.py
=> Limiting graph size at 2M by default

.github/workflows/stale.yaml
=> Adding workflow for staling and closing issue

trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/asm.py, trueseeing/core/literalquery.py, trueseeing/core/patch.py, trueseeing/core/report.py, trueseeing/core/sign.py, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py
=> Migrating to importlib

pyproject.toml
=> Updating dependencies

.github/workflows/deploy.yaml, .github/workflows/lint.yaml, README.md
=> Revised documentation

trueseeing/app/inspect.py
=> Soft-map bools

trueseeing/app/inspect.py
=> Reading version

trueseeing/app/inspect.py, trueseeing/app/shell.py
=> Accepting command/script

trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/ui.py
=> Dropping implicit scan mode

README.md, trueseeing/app/shell.py
=> Updating docs

trueseeing/app/inspect.py
=> Decorating output if we can

trueseeing/app/inspect.py
=> Removing inspect mode indicator

pyproject.toml
=> Adding private classifier

pyproject.toml
=> Use recognized private category

trueseeing/core/code/parse.py, trueseeing/core/ui.py
=> Suppress in-place indicators in batch mode

trueseeing/app/shell.py
=> Introduced an option to target /dev/null

README.md, trueseeing/app/inspect.py, trueseeing/core/asm.py, trueseeing/core/context.py
=> Levelling analysis

trueseeing/app/shell.py
=> Reflect command change in help text

trueseeing/app/shell.py
=> Migrating to argparse

trueseeing/app/shell.py, trueseeing/core/flow/data.py, trueseeing/signature/fingerprint.py
=> Adding fairly naive reflection detector

trueseeing/signature/fingerprint.py
=> Obfuscator detection should be more permissive

trueseeing/signature/manifest.py
=> Considering exported attr on BRs with intent filter

trueseeing/app/inspect.py, trueseeing/app/scan.py, trueseeing/core/issue.py, trueseeing/core/literalquery.py, trueseeing/libs/store.1.sql
=> Storing issues at most once, and clear issues only if needed

trueseeing/app/inspect.py, trueseeing/core/literalquery.py
=> Accepting patterns at co

trueseeing/core/literalquery.py, trueseeing/core/report.py, trueseeing/libs/template/report.html
=> Revising HTML/JSON report format

Dockerfile, README.md, pyproject.toml, trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/api.py, trueseeing/core/asm.py, trueseeing/core/context.py, trueseeing/core/device.py, trueseeing/core/env.py, trueseeing/core/literalquery.py, trueseeing/core/report.py, trueseeing/core/sign.py, trueseeing/core/tools.py, trueseeing/core/ui.py, trueseeing/libs/files.0.sql, trueseeing/libs/store.0.sql, trueseeing/signature/fingerprint.py, trueseeing/signature/manifest.py
=> Re-enabling non-container installation

README.md
=> Described how to run in non-container installation

Dockerfile, README.md, trueseeing/core/api.py, trueseeing/core/env.py
=> Restoring extension mechanism

pyproject.toml, trueseeing/core/asm.py, trueseeing/core/code/parse.py, trueseeing/core/context.py, trueseeing/core/literalquery.py, trueseeing/core/tools.py, trueseeing/core/ui.py
=> Experimentally introducing progressbar2

trueseeing/app/inspect.py
=> iii should trigger a full analysis

trueseeing/app/inspect.py
=> Allowing aliases/macros

trueseeing/app/shell.py, trueseeing/core/env.py
=> Reading startup file

trueseeing/app/inspect.py
=> Adding quit command

trueseeing/app/inspect.py
=> Fixing exception handling

trueseeing/libs/LICENSE.md
=> Mentioning 3rd party code licenses

trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/api.py, trueseeing/core/context.py
=> Inspecting extensions

pyproject.toml, trueseeing/app/shell.py, trueseeing/core/api.py, trueseeing/core/env.py
=> Looking for extension packages

trueseeing/api.py, trueseeing/app/cmd/__init__.py, trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/ext.py, trueseeing/core/model/cmd.py, trueseeing/core/tools.py, trueseeing/sig/__init__.py
=> Optionally aborting on errors

trueseeing/core/android/db.py, trueseeing/core/cvss.py, trueseeing/core/model/issue.py, trueseeing/core/report.py, trueseeing/libs/android/store.1.sql, trueseeing/libs/template/report.html, trueseeing/sig/android/fingerprint.py
=> Do not group issues with actual CVSS score

pyproject.toml, trueseeing/sig/android/crypto.py
=> Experimentally evaluating ASN.1 like data

trueseeing/sig/android/security.py
=> Slightly better root-detect detection

trueseeing/core/report.py, trueseeing/libs/template/report.html
=> Cutting long lines at 256 chars

trueseeing/sig/android/fingerprint.py
=> Experimentally culling common non-informations

trueseeing/core/android/db.py, trueseeing/core/model/issue.py, trueseeing/core/report.py, trueseeing/core/ui.py
=> Do not note duplicated issues

pyproject.toml, trueseeing/sig/android/crypto.py
=> Testing keys with in ASN.1 context

trueseeing/app/inspect.py, trueseeing/app/scan.py, trueseeing/core/android/asm.py, trueseeing/core/android/context.py, trueseeing/core/android/db.py, trueseeing/core/android/store.py, trueseeing/core/env.py, trueseeing/core/exc.py
=> Marking schema version

trueseeing/app/cmd/android/asm.py, trueseeing/core/tools.py
=> Overhauling ca/cd/co

trueseeing/app/cmd/android/asm.py
=> Fixing message

trueseeing/core/report.py
=> Ditching old notation

trueseeing/core/ext.py
=> Discovering *.pth style packages by our own

trueseeing/app/cmd/__init__.py, trueseeing/core/tools.py, trueseeing/sig/__init__.py
=> Loading pyc as well

trueseeing/core/tools.py
=> Do not attempt to load invalid or magical files

trueseeing/core/report.py, trueseeing/libs/template/report.html
=> Trimming whitespace

trueseeing/api.py, trueseeing/app/cmd/android/show.py, trueseeing/app/inspect.py, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/android/analysis/flow.py, trueseeing/core/android/analysis/smali.py, trueseeing/core/android/db.py, trueseeing/core/android/store.py, trueseeing/core/context.py, trueseeing/core/exc.py, trueseeing/core/ext.py, trueseeing/core/scan.py, trueseeing/sig/android/crypto.py, trueseeing/sig/android/fingerprint.py, trueseeing/sig/android/privacy.py, trueseeing/sig/android/security.py
=> De-coupling file format handling logic, and more refactoring

README.md, trueseeing/api.py, trueseeing/app/inspect.py, trueseeing/core/android/analysis/flow.py, trueseeing/core/ext.py, trueseeing/core/model/sig.py
=> Code cleanups

trueseeing/app/cmd/analyze.py, trueseeing/app/cmd/android/asm.py, trueseeing/app/cmd/android/exploit.py, trueseeing/app/cmd/android/search.py, trueseeing/app/cmd/android/show.py, trueseeing/app/cmd/config.py, trueseeing/app/cmd/info.py, trueseeing/app/inspect.py, trueseeing/core/exc.py, trueseeing/core/scan.py
=> More code cleanups

trueseeing/app/cmd/android/search.py, trueseeing/app/cmd/android/show.py, trueseeing/app/cmd/search.py, trueseeing/app/cmd/show.py, trueseeing/core/context.py, trueseeing/sig/android/fingerprint.py, trueseeing/sig/android/security.py
=> Ensuring to require relevant context type

trueseeing/app/cmd/search.py
=> Adding text mode operation of /s

trueseeing/app/cmd/search.py
=> Updated command description

pyproject.toml, trueseeing/app/cmd/android/exploit.py, trueseeing/core/android/asm.py, trueseeing/core/android/db.py, trueseeing/core/android/store.py, trueseeing/core/env.py, trueseeing/libs/files.0.sql
=> Experimentally compressing benign corpus

trueseeing/core/android/context.py, trueseeing/core/context.py
=> Extracting context base implementation

trueseeing/core/db.py, trueseeing/core/store.py, trueseeing/core/z.py
=> Applying compression beforehand

trueseeing/core/db.py, trueseeing/core/store.py
=> Decompressing on our side as well

trueseeing/core/scan.py
=> Unmatches should not negate matches

trueseeing/core/db.py
=> Factored out cache schema ID generation logic

trueseeing/app/shell.py
=> Adding quieter mode

trueseeing/app/cmd/info.py, trueseeing/core/android/context.py, trueseeing/core/context.py
=> Contexts weigh themselves

trueseeing/sig/android/crypto.py
=> Do not crash on invalid undecodable base64 string

trueseeing/app/cmd/info.py, trueseeing/core/android/context.py, trueseeing/core/context.py
=> Contexts provides info

trueseeing/app/cmd/android/show.py
=> Printing class/method with qualname

trueseeing/app/cmd/android/search.py, trueseeing/app/cmd/android/show.py
=> Search commands should output in meaningful format

trueseeing/app/cmd/android/device.py, trueseeing/app/cmd/config.py, trueseeing/app/inspect.py, trueseeing/core/android/context.py, trueseeing/core/tools.py, trueseeing/core/ui.py
=> Experimentally adding dynamic analysis basis

trueseeing/sig/android/fingerprint.py
=> Detecting the simplest form of authentication

trueseeing/core/db.py
=> Properly decompressing patched-in blobs

pyproject.toml, trueseeing/app/cmd/android/device.py, trueseeing/app/cmd/android/exploit.py, trueseeing/core/env.py, trueseeing/libs/android/frida-app.smali, trueseeing/libs/android/frida-scriptdir.config
=> Expeimentally injecting frida-gadget

Dockerfile
=> Building LIEF

Dockerfile
=> Pulling the prebuilt wheel instead of building

trueseeing/app/cmd/scan.py, trueseeing/core/scan.py
=> Aborting scanning on invalid scanner configurations

trueseeing/api.py, trueseeing/app/inspect.py, trueseeing/app/scan.py, trueseeing/app/shell.py, trueseeing/core/context.py
=> Enabling to select opener

trueseeing/app/cmd/android/exploit.py
=> Handling network failure

trueseeing/app/cmd/android/search.py, trueseeing/app/cmd/android/show.py, trueseeing/core/android/analysis/flow.py, trueseeing/core/android/db.py, trueseeing/core/ui.py
=> Better wording

trueseeing/core/android/asm.py, trueseeing/core/android/context.py, trueseeing/core/context.py
=> Do not cache target

trueseeing/core/android/context.py, trueseeing/core/android/db.py, trueseeing/core/context.py, trueseeing/core/store.py
=> Using path based FP

trueseeing/app/cmd/android/show.py, trueseeing/app/inspect.py, trueseeing/core/android/analysis/flow.py
=> CLI fixups

trueseeing/app/cmd/android/engage.py, trueseeing/core/tools.py, trueseeing/core/ui.py
=> Adding install/uninstall command

trueseeing/app/cmd/android/recon.py, trueseeing/core/android/device.py
=> Adding device shell

trueseeing/app/cmd/android/engage.py, trueseeing/app/cmd/android/recon.py
=> Defining options in correct module

pyproject.toml, trueseeing/core/android/context.py, trueseeing/core/tools.py
=> Considering package name on generating FP

trueseeing/app/cmd/android/engage.py, trueseeing/app/cmd/android/recon.py
=> Now we can take package name nearly free

trueseeing/core/tools.py
=> Experimentally flattening buffer in finding newlines

pyproject.toml, trueseeing/api.py, trueseeing/app/cmd/config.py, trueseeing/app/cmd/scan.py, trueseeing/app/inspect.py
=> Enabling to bind configs for commands

trueseeing/core/android/asm.py, trueseeing/core/android/context.py
=> Also caching v0 fingerprint

trueseeing/core/android/analysis/flow.py
=> Fixing error reporting

trueseeing/core/android/context.py, trueseeing/core/context.py
=> Verifiable FP, and API fixup

trueseeing/app/cmd/android/engage.py
=> Experimentally reviving apk grabber

trueseeing/app/cmd/android/asm.py, trueseeing/app/cmd/android/engage.py, trueseeing/core/android/asm.py, trueseeing/core/android/context.py, trueseeing/core/android/model.py, trueseeing/core/context.py
=> Experimentally supporting xapk

pyproject.toml, trueseeing/app/inspect.py
=> Handling input with prompt-toolkit

trueseeing/app/cmd/search.py
=> Do not abort on non-UTF-8 texts

trueseeing/app/inspect.py, trueseeing/app/shell.py, trueseeing/core/context.py
=> Listing file formats

trueseeing/core/android/context.py
=> Aligning type before comparison

trueseeing/core/android/context.py
=> Quoting merging input path

trueseeing/core/android/context.py
=> Fixing failed assertion

trueseeing/core/ext.py
=> Optionally looking 2-level deep

trueseeing/app/cmd/android/asm.py
=> Setting member size

trueseeing/app/cmd/android/engage.py
=> Patching xapks as merged apks

trueseeing/app/cmd/android/asm.py, trueseeing/core/android/asm.py, trueseeing/core/android/context.py
=> Experimentally adding command to merge slices

trueseeing/app/cmd/android/asm.py
=> Merge slices into given path

trueseeing/app/cmd/android/recon.py
=> Do not require context unless need to

trueseeing/app/cmd/android/engage.py, trueseeing/core/android/asm.py, trueseeing/core/android/context.py
=> Quoting pathes

trueseeing/app/cmd/android/engage.py, trueseeing/app/cmd/android/recon.py, trueseeing/core/android/device.py
=> Using the single-quote for quoting device shell cmdline

trueseeing/core/context.py, trueseeing/core/ios/analyze.py, trueseeing/core/ios/context.py, trueseeing/core/ios/db.py, trueseeing/core/ios/model.py, trueseeing/core/ios/store.py, trueseeing/core/ios/swift.py, trueseeing/libs/ios/store.0.sql, trueseeing/libs/ios/store.1.sql, trueseeing/sig/ios/base.py
=> Experimentally analyzing iOS app

trueseeing/core/android/context.py, trueseeing/core/context.py, trueseeing/core/ios/context.py
=> Caching fingerprint for iOS apps too

trueseeing/core/ios/context.py
=> Using pubsub for iOS too

trueseeing/core/android/db.py, trueseeing/libs/android/store.1.sql
=> Adding index for section

.github/workflows/deploy.yaml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, Dockerfile, pyproject.toml
=> Migrating to Python 3.13

Dockerfile
=> Writable mountpoints should be permissive

trueseeing/core/android/context.py, trueseeing/core/ios/context.py
=> Showing guidance for native code disassembling facility

trueseeing/app/cmd/android/engage.py
=> Experimentally injecting frida-server

trueseeing/app/cmd/android/engage.py
=> Updated option help

trueseeing/app/inspect.py, trueseeing/app/shell.py
=> Unmasking exceptions in debug mode

Dockerfile, pyproject.toml
=> Requiring frida-tools

trueseeing/app/cmd/android/engage.py
=> xs/xk should control frida-server and frida

trueseeing/app/cmd/android/engage.py
=> Fixing frida-server feel URL

trueseeing/app/cmd/android/engage.py
=> Controlling frida-server properly

trueseeing/app/cmd/android/engage.py, trueseeing/core/android/device.py, trueseeing/core/tools.py
=> Calling frida properly

trueseeing/app/cmd/android/engage.py, trueseeing/core/ui.py
=> Enabling to attach frida to active processes

trueseeing/app/cmd/android/engage.py
=> Fixing root detection

trueseeing/app/cmd/android/engage.py
=> Unblocking targetless xs on non-rooted devices

trueseeing/app/cmd/android/engage.py
=> Experimentally adding call tracing command

trueseeing/app/cmd/android/engage.py
=> Forcing prompted attach on non-rooted device

trueseeing/app/cmd/android/engage.py
=> Do not give up if we cannot contact remote frida fanout server

trueseeing/app/cmd/ios/engage.py, trueseeing/core/env.py, trueseeing/core/ios/context.py, trueseeing/core/ios/device.py
=> Experimentally driving frida on iOS

trueseeing/app/cmd/android/engage.py, trueseeing/app/cmd/ios/engage.py, trueseeing/app/inspect.py
=> Introducing frida shell

Dockerfile, trueseeing/app/cmd/ios/engage.py, trueseeing/core/env.py
=> Experimentally grabbing packages on iOS (powered by frida-ios-dump)

trueseeing/api.py, trueseeing/core/context.py
=> Making t requisite

Dockerfile, trueseeing/app/cmd/ios/engage.py, trueseeing/core/env.py
=> Connecting to devices in more robust manner

trueseeing/app/cmd/android/recon.py, trueseeing/app/cmd/ios/recon.py
=> Porting package lister to iOS

trueseeing/app/cmd/android/engage.py, trueseeing/app/inspect.py, trueseeing/core/nat.py
=> Ignoring uninstallation errors when we're in force

trueseeing/app/cmd/android/engage.py
=> Adjusting required analysis level

Dockerfile
=> Pinning Python version
